name: Publish on PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  main:
    name: publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python
        run: uv python install
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
